import { NgxUiLoaderConfig } from "ngx-ui-loader";

export const ngxUiLoaderConfig: NgxUiLoaderConfig = {
    "bgsColor": "#ffffff",
    "bgsOpacity": 0.5,
    "bgsPosition": "bottom-right",
    "bgsSize": 60,
    "bgsType": "ball-spin-clockwise",
    "blur": 5,
    "delay": 0,
    "fastFadeOut": true,
    "fgsColor": "#2A4B70",
    "fgsPosition": "center-center",
    "fgsSize": 60,
    "gap": 24,
    "logoPosition": "center-center",
    "logoSize": 250,
    "logoUrl": "../../assets/PN_logo-2.png",
    "masterLoaderId": "master",
    "overlayBorderRadius": "0",
    "overlayColor": "#cacacac3",
    "pbColor": "red",
    "pbDirection": "ltr",
    "pbThickness": 3,
    "hasProgressBar": false,
    "text": "Cargando...",
    "textColor": "#2A4B70",
    "textPosition": "center-center",
    "maxTime": -1,
    "minTime": 300
}